name: Daily Sync _worker.js from upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 零点运行
  workflow_dispatch:

jobs:
  sync_worker:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 检出当前仓库
        uses: actions/checkout@v3

      - name: 获取上游最新 SHA
        id: get_sha
        run: |
          SHA=$(curl -s https://api.github.com/repos/ImLTHQ/edgetunnel-tianshu/commits/main | grep '"sha"' | head -n 1 | cut -d '"' -f 4)
          echo "$SHA" > upstream_sha.txt
          echo "sha=$SHA" >> "$GITHUB_OUTPUT"

      - name: 检查是否需要更新
        id: check_update
        run: |
          if [ ! -f version.txt ]; then
            echo "首次运行，需更新"
            echo "need_update=true" >> "$GITHUB_OUTPUT"
          elif ! cmp -s upstream_sha.txt version.txt; then
            echo "SHA 不匹配，需更新"
            echo "need_update=true" >> "$GITHUB_OUTPUT"
          else
            echo "SHA 匹配，无需更新"
            echo "need_update=false" >> "$GITHUB_OUTPUT"
          fi

      - name: 下载 _worker.js
        if: steps.check_update.outputs.need_update == 'true'
        run: |
          curl -sL https://raw.githubusercontent.com/ImLTHQ/edgetunnel-tianshu/main/_worker.js -o _worker.js
          cp upstream_sha.txt version.txt

      - name: 提交更新
        if: steps.check_update.outputs.need_update == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add _worker.js version.txt
          git commit -m "chore: sync _worker.js from upstream SHA $(cat version.txt)" || echo "无变更可提交"
          git push
